version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOSTNAME=0.0.0.0
    volumes:
      # Монтируем только необходимые файлы для production
      - ./public:/app/public:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Для разработки можно добавить backend сервис
  # backend:
  #   image: your-backend-image:latest
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - NODE_ENV=production
  #   restart: unless-stopped

networks:
  default:
    name: callcentre-network
